### ISSUE TITLE
Build instructions seem to be out of date

### ISSUE THREAD

**Issue by swrobel** [mailhog/MailHog#100]
Context: I'm [trying to update](https://github.com/Homebrew/homebrew-core/issues/2501) the very convoluted [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mailhog.rb) for mailhog that builds from source

I'm not very familiar with go package management/vendoring or build processes, but [these build instructions](https://github.com/mailhog/MailHog/blob/master/docs/BUILD.md) seem to be out-of-date since [assets.go](https://github.com/mailhog/MailHog/blob/master/docs/MailHog-UI/assets/assets.go) is no longer committed to the repo.

**Comment by ian-kent** [comment]
I'd agree, the build process is a bit complicated!

[assets.go](https://github.com/mailhog/MailHog-UI/blob/master/assets/assets.go) is still committed to the repo, but the path in the documentation was wrong (not sure if that's because it moved, or if I just got it wrong when I wrote the docs)

Just read through the homebrew issue, switching to vendoring is a good idea, I'll do it asap! MailHog _should_ build against the latest versions of all deps (tested it using Vagrant for #103, which would have used the latest versions)

It might have been the broken import paths for mgo, which were still using an old http server instead of gopkg.in

**Comment by ian-kent** [comment]
dependencies are now vendored, hopefully should help with Homebrew/homebrew-core#2501
