### ISSUE TITLE
outgoing smtp json config parsing fails

### ISSUE THREAD

**Issue by guycalledseven** [mailhog/MailHog#112]
Thanks for cool project! 

I am using MailHog via Docker and trying to set up SMTP relay functionality to my MT. 
I am setting env MH_OUTGOING_SMTP to the file I previously ADD-ed to my MailHog container via Dockefile.

MailHog is complaining about the json format, and I am using json format from the docs:

```
{
    "server": {
        "name": "server",
        "host": "...",
        "port": "587",
        "email": "...",
        "username": "...",
        "password": "...",
        "mechanism": "PLAIN"
    }
}
```

The error I am getting is this:

```
2016/09/09 11:21:00 Using in-memory storage
2016/09/09 11:21:00 invalid character '/' after top-level value
```

I made it work but had to strip whitespace:

```
{
"server": {
"name": "server",
...
"username": "...",
"password": "...",
"mechanism": "PLAIN"
}
}
```

 It seems to me that issue originates in  mgo json scanner in package you used (mgo.v2/internal/json/scanner.go). I am not using mongo, so I don't' know why they do this at all with json and not trust golangs json parser to be able to parse json.

stateEndTop doesn't handle whitespace in this check:
https://github.com/mailhog/MailHog/blob/c68ed81a0c45a8df23e2c60d110d470a17dffab3/vendor/gopkg.in/mgo.v2/internal/json/scanner.go#L340

I don't know if this is my issue due to different versions of golang/oses I am using (i am using golang 1.7.1), or this is actually how it should be implemented. 

In each case **I would recommend against using .json for config, and suggest using additional environment variables**.  I don't like much hardcoding config files with passwords and Docker compose with environment vars/files do more or less good job in keeping configs.

Best

edit: tldr bold :)

**Comment by ian-kent** [comment]
I'm not too sure how the mgo scanner would be used instead of `encoding/json`, it's loaded [here](https://github.com/mailhog/MailHog-Server/blob/master/config/config.go#L102) which is using the standard library package.

I've just tried it locally, and it works ok for me for the example above:
```bash
➜  MailHog git:(master) ✗ cat outgoing.json 
{
    "server": {
        "name": "server",
        "host": "...",
        "port": "587",
        "email": "...",
        "username": "...",
        "password": "...",
        "mechanism": "PLAIN"
    }
}

➜  MailHog git:(master) ✗ MailHog -outgoing-smtp "outgoing.json"
2016/11/14 23:22:26 Using in-memory storage
2016/11/14 23:22:26 [SMTP] Binding to address: 0.0.0.0:1025
[HTTP] Binding to address: 0.0.0.0:8025
2016/11/14 23:22:26 Serving under http://0.0.0.0:8025/
Creating API v1 with WebPath: 
Creating API v2 with WebPath: 
^C
```

I wouldn't normally use a file for the config, but it made sense for this for a couple of reasons:
* there could be any number of outgoing SMTP servers, environment variables could work but could get messy
* the intention was to allow creating/removing them from the UI/API so they persist between restarts, which never materialised

It might be better for outgoing SMTP servers to have a similar backend storage as mail does, making it easy to support a database etc too

**Comment by ian-kent** [comment]
I'll close this, but if it becomes an issue again let me know
