### ISSUE TITLE
Trojan Gen:Variant.Graftor.369260 ?

### ISSUE THREAD

**Issue by crazy-max** [mailhog/MailHog#154]
Hi,

A user of [Neard](http://neard.io) indicates a Bit Defender alert (crazy-max/neard#278).
I have made a [virustotal scan](https://www.virustotal.com/fr/file/0c0e85b6e66e8f43318a298531a9a9d8aad98ef77744042f7c3049970bb57e42/analysis/) and it indicates the presence of a trojan of Graftor type (PUP?). False positive ?

Thanks!

![image](https://user-images.githubusercontent.com/1951866/27176065-7a8b8820-51c1-11e7-9eca-b3bd90adc4b1.png)

**Comment by crazy-max** [comment]
Some feedback about this issue please ?

**Comment by ian-kent** [comment]
Hi @crazy-max 

There shouldn't be any reason for MailHog to fail, so I'd expect its a false positive - since it's a generic detector which uses heuristics, it's difficult to pinpoint exactly what inside MailHog could triggering it.

I'm confident the MailHog codebase itself is clean, but without manually inspecting the code for every dependency it uses I couldn't 100% guarantee the output binaries are.

I'd have to go with the 'at your own risk' advice until I have a chance to fully investigate, but thanks for flagging it up!

**Comment by crazy-max** [comment]
Hi @ian-kent,

Thanks for your answer but yeah it seems to be a PUP
