### ISSUE TITLE
Feature: reject invalid recipient emails

### ISSUE THREAD

**Issue by swrobel** [mailhog/MailHog#163]
"Real" SMTP servers will reject invalid recipient emails, but you can send an email to 'test' with Mailhog and it's accepted. I think it will be a much more useful testing platform if it behaves like the real world and throws a delivery error on invalid email address or empty recipient.

**Comment by mkrsn** [comment]
Hi,

you're mistaken - "test" is a valid mail-address!

It's the local part of the address and addresses always a local User on the receiving Server. Because of MailHog doesn't know anything about local User it **should** accept such kind of Mails.

You can easily proof it with a Linux-PC

> useradd atestuser
> 
> nc 127.0.0.1 25 <<EOF
> > EHLO localhost.localdomain
> > MAIL FROM:some-valid-mail@example.net
> > RCPT TO:atestuser
> > data
> > Subject: Testmail
> > This is a Test!
> > 
> > .
> > EOF
>
> cat /var/spool/mail/atestuser


Best Regards

Matthias

**Comment by tyndyll** [comment]
@swrobel Can you paste a SMTP session which demonstrates your expected result? (e.g. https://docs.microsoft.com/en-us/exchange/mail-flow/test-smtp-with-telnet?view=exchserver-2019)

**Comment by allangood** [comment]
Hi @swrobel, I believe you are talking about validate e-mail address based on all RFCs.
Based on this assumption, a regular expression can be used to [validate e-mails](http://emailregex.com/email-validation-summary/index.html) but this will introduce a new challenge/problem described [here](https://www.regular-expressions.info/email.html). In summary, any regular expression will not be UTF-8 safe (think on people on Japan for instance). The regular expression needs to validate user/domains in all possible language.

Or, maybe, instead of "validation", just do some small verification like non empty value and presence of "@" signal (but then the test made by @mkrsn will be broken).

**Comment by swrobel** [comment]
Thanks for the feedback, everyone. I now realize that the issue of recipient validation is much more complex and non-standard than I imagined, rather than being a simple spec that all SMTP servers could follow. I'm going to close this out.

**Comment by tyndyll** [comment]
@swrobel Thanks for your feedback and suggestion.
