### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by benlumia007** [mailhog/MailHog#254]
Is the container for mailhog only has mailhog, does it also have mhsendmail or do i need to add mhsendmail, i try everything i can think, i even try to install on fpm and nginx.

im not sure where I'm doing wrong.

**Comment by samhwang** [comment]
No, `mhsendmail` is not included in the `mailhog/mailhog` docker container. You will need to download mhsendmail (by either `curl` or `go get`) in the container that you are planning to send email from. 

For example, I have a PHP container, and a mailhog container, to connect between the two, I need to include this in the PHP image dockerfile:

```Dockerfile
RUN curl -LkSso /usr/bin/mhsendmail 'https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64'&& \
    chmod 0755 /usr/bin/mhsendmail && \
    echo 'sendmail_path = "/usr/bin/mhsendmail --smtp-addr=mailhog:1025"' > /usr/local/etc/php/php.ini;
```

**Comment by benlumia007** [comment]
Then, I do have couple of things I want to share. when i do a go get, assuming that i have to download the go packages as well. with the one with the mhsendmail that uses go get, i see that it has the following
```
Usage of mhsendmail:
  -f, --from string        SMTP sender (default "root@e0a286d79302")
  -i, --long-i             Ignored. This flag exists for sendmail compatibility. (default true)
  -o, --long-o             Ignored. This flag exists for sendmail compatibility. (default true)
  -t, --long-t             Ignored. This flag exists for sendmail compatibility. (default true)
      --smtp-addr string   SMTP server address (default "localhost:1025")
  -v, --verbose            Verbose mode (sends debug output to stderr)
```
rather if i do a curl, it doesn't have all this preset, so it asks me to set up --from and --smtp-addr.  so i couldn't use the curl.. it seems like is not the same version. is it because of the docker version is different from the one that uses curl

**Comment by benlumia007** [comment]
i didn't wanna use the go get because, it downloads 200MB worth of go packages just to get mhsendmail, i feel like this is really silly. so what i did was i jsut took mhsendmail copy it over to my project and create and add mhsendmail to project. without go.

**Comment by samhwang** [comment]
The way you could do it with curl was there in the example code bit. Let me clarify. Those instructions will:

- Curl the `mhsendmail` binary into /usr/bin/mhsendmail in your PHP container
- Change the `mhsendmail` binary mode to 0755, making it executable.
- Add the mhsendmail configuration into PHP. 

Instead of using sendmail when the PHP `mail()` function is called, PHP will now use `/usr/bin/mhsendmail` as a replacement for `sendmail`. The `--smtp-addr=mailhog:1025` bit points to the `mailhog` container was the port needed to be exposed to send the mail into. You can also set the `--from=your_email@email_host.com` to by adding a parameter before echoing into `php.ini`. 

From that point, you can test the mail function by running this command inside the container:

```bash
$ php -r "mail('recipient@mail.com', 'test subject', 'test body');"
```

If done correctly, when you go to `localhost:8025` (or whatever port you're mapping your mailhog container to), it will show the email that you just "sent". (The sender here is "nobody" because I didn't put in a `--from` in the config).

<img width="383" alt="Screen Shot 2019-09-17 at 8 40 20 pm" src="https://user-images.githubusercontent.com/4188758/65034962-68983d80-d98b-11e9-8de8-db02ade3c64b.png">

**Comment by samhwang** [comment]
Also, I understand the bit where you said you don't want to do `go get` to avoid downloading a bunch of stuff you don't need. I get that, which is why I also chose to do a curl in my own image.

The "preset" you said, is actually what shows when you don't have the parameters set up, which also applies when you do a `go get` anyway. `go get` is not something to do with docker at all, it's actually downloading the [mailhog/mhsendmail](https://github.com/mailhog/mhsendmail) github repository, and then by that instruction link, they also just copy the binary into `/usr/bin` and echoing the config into `php.ini`. The main difference between the `go get` and the `curl` method is one method download the whole code repository, the other one just download the binary.

Not everything in that "preset" you posted on here is needed (they even said so themselves, "Ignored. This flag exists for sendmail compatibilty"). The part you really need to focus on is setting the parameters for `--from` and `--smtp-addr`, which also shows up even if you are downloading just the binary by curling. This is what shows up if I run the `mhsendmail --help` command in the container.

<img width="956" alt="Screen Shot 2019-09-17 at 8 42 30 pm" src="https://user-images.githubusercontent.com/4188758/65035476-a34ea580-d98c-11e9-90c8-95808cb2aec8.png">

**Comment by samhwang** [comment]
To sum up my bunch of long comments are:

- The `mailhog/mailhog` container on dockerhub does not come with mhsendmail.
- You will need to install the `mhsendmail` binary in your own backend container, either by curling or `go get`.
- You will also need to configure it to connect to the `mailhog` container, and run the 2 containers side by side. For PHP, this is configured in the `php.ini` file.

**Comment by benlumia007** [comment]
thanks, sam for pointing me in the right direction. I'll try again by using curl and fixed the parameters. closing ticket as resolved.

**Comment by achraf-jeday** [comment]
Hello guys I was having trouble with php sendmail configuration and unable to send emails to the mailhog container but thanks to @samhwang I managed to make it work.

I wanted to point out that the php and the mailhog containers have to share the same network otherwise you will get the _"no such host"_ error message when you try to send an email from php:

`dial tcp: lookup mailhog on 127.0.0.11:53: no such host`

**Comment by jleask** [comment]
> No, `mhsendmail` is not included in the `mailhog/mailhog` docker container. You will need to download `mhsendmail` (by either `curl` or `go get`) in the container that you are planning to send email from.
> 
> For example, I have a PHP container, and a mailhog container, to connect between the two, I need to include this in the PHP image dockerfile:
> 
> ```dockerfile
> RUN curl -LkSso /usr/bin/mhsendmail 'https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64'&& \
>     chmod 0755 /usr/bin/mhsendmail && \
>     echo 'sendmail_path = "/usr/bin/mhsendmail --smtp-addr=mailhog:1025"' > /usr/local/etc/php/php.ini;
> ```
> 
> For instructions on installing with `go get`, have a look here: https://phauer.com/2017/test-mail-server-php-docker-container/

Than you so much for the instructions on how to install mhsendmail with curl. I really wish this information was available directly on the Mailhog and/or the mhsendmail pages. We need to add mhsendmail to a container, and finding out how to do it was difficult.
