### ISSUE TITLE
Doc Request: smtp forwarding and API V2

### ISSUE THREAD

**Issue by GilpinGambler** [mailhog/MailHog#36]
Let me start by saying I love mailhog.  I just found it and got it up and running in no time.  Great work!  I'd like to take advantage of the feature to forward messages to an SMTP server, but I don't know how to set that up.  I didn't see it in the CONFIG.md file.  I don't know Go (I'm a Java dev), but I found the following snippet in the config.go file from the Server repo: 

flag.StringVar(&cfg.OutgoingSMTPFile, "outgoing-smtp", envconf.FromEnvP("MH_OUTGOING_SMTP", "").(string), "JSON file containing outgoing SMTP servers")

So, I know I need a file with JSON, but what is the expected format?

Also, I noticed that when using the web client I could see the API calls to the server, which is cool, but I noticed that it uses v2.  The docs are still for v1.  I think I can get most of what I need from the server output, but I was wondering if there were other nuggets of gold I hadn't discovered.  For example, the docs don't cover search requests, but I was able to see them when using the search feature in the UI.

If you could update the docs to include the above information, that would be awesome.

Thanks!

**Comment by ian-kent** [comment]
Yeah the documentation could be a lot better :smile: I'll hopefully get around to updating it this weekend! I think you've found everything though!

The SMTP auth stuff is [very briefly documented here](https://github.com/mailhog/MailHog/issues/15). Summary is - you can configure via the UI and reuse the config later in the same session, but it doesn't get persisted. You can specify a JSON file (so they're always available), but they can't be modified in the UI. Basically, the SMTP AUTH stuff is all a bit hacked in because I wasn't entirely sure about the use case for it!

The JSON file format is [based on this](https://github.com/mailhog/MailHog-Server/blob/master/config/config.go#L48-L57), so something along the lines of:
```json
{
    "server name": {
        "name": "server name",
        "host": "...",
        "port": 587,
        "username": "...",
        "password": "...",
        "mechanism": "PLAIN",
    }
}
```

not sure what logic was behind me requiring server name twice - or if its even used - this is where documenting it would have helped :wink:

**Comment by GilpinGambler** [comment]
Thanks for getting back to me.  I got it working.
