### ISSUE TITLE
MailHog doesn't send the emails

### ISSUE THREAD

**Issue by joseraeiro** [mailhog/MailHog#419]
Hi! 

I've tried to use MailHog as an SMTP server to be able to send emails. I followed the installation instructions and the HTTP server does show the emails sent but no email is received on the accounts it said it was sent to. Please look at the following screenshot https://ibb.co/TPgtMZq

What am I doing wrong?

**Comment by ap-wtioit** [comment]
If you open github issues, please upload screenshots directly, not in a strange viewer.

MailHog does not send mails, it receives them and displays them as HTML for testing your SMTP code without the need for a real e-mail server. If you want to send mails (which it seems you are already doing, since MailHog is receiving them) send them either directly to the correct server (indicated by the domains MX entry) or use a relay server (e.g. postfix, https://github.com/docker-mailserver/docker-mailserver)

**Comment by joseraeiro** [comment]
Thank you very much for the clarification!
