### ISSUE TITLE
Mail subject utf8 error

### ISSUE THREAD

**Issue by NamPNQ** [mailhog/MailHog#46]
Subject	=?utf-8?q?I=27some_test?=

**Comment by chalasr** [comment]
Hi,

I'm facing a similar issue when trying to fetch mails from the Api (v2).
Performing a query on `/api/v2/search` using `containing` on the subject of a mail gives an empty result.

For instance I search: `'containing' => 'Your free product'`, but in fact the subject appears as `Your free =?utf-8?Q?product=0A?=` when fetching all mails.

Could it be possible to do something for clean up the subject as it is done for the web interface, in order to allow performing `containing` queries on?
Thank you
