### ISSUE TITLE
Feature Request: Internet Explorer Support

### ISSUE THREAD

**Issue by wespday** [mailhog/MailHog#58]
The site doesn't work in Internet Explorer.
The script debugger shows an error: 'EventSource' is undefined.

According to StackOverflow IE doesn't support this:

http://stackoverflow.com/questions/24498141/is-there-a-microsoft-equivalent-for-html5-server-sent-events

They also suggest a work-around:
https://github.com/remy/polyfills/blob/master/EventSource.js

**Comment by ian-kent** [comment]
Hi @wespday - which version of IE are you using?

My first suggestion would be to upgrade or not use IE :grinning: but I realise that's not always possible!

I'm not entirely convinced about supporting older browsers (sounds like a potential maintenance nightmare), but if its just this polyfill I wouldn't mind too much.

I'll have a look when I get a chance, otherwise PRs are welcome!

**Comment by wespday** [comment]
I'm on IE11

**Comment by ian-kent** [comment]
> I'm on IE11

:sob: didn't realise new IE didn't support it either! polyfill it is!

**Comment by ian-kent** [comment]
i'll leave this for now - i read the link you posted, websockets would be a much better solution, and would work in all new browsers (so no need to maintain event stream code) - i'll do that instead, it'll just take longer!

**Comment by TigerWolf** [comment]
One of our testers is testing on IE 11 and the HTML display is not working. Most things work except for the HTML tab (plain text and source work).

It appears that the iframe srcdoc= is not working? 

Maybe add this? https://github.com/jugglinmike/srcdoc-polyfill
